### ISSUE TITLE
Maven is not building

### ISSUE THREAD

**Issue by gaspo53** [luanne/flavorwocky#18]
$ mvn clean spring-boot:run
[INFO] Scanning for projects...
[WARNING] The POM for org.springframework.boot:spring-boot-maven-plugin:jar:1.3.0.M5 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.springframework.boot:spring-boot-maven-plugin:1.3.0.M5: Plugin org.springframework.boot:spring-boot-maven-plugin:1.3.0.M5 or one of its dependencies could not be resolved: Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:1.3.0.M5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.springframework.boot:spring-boot-maven-plugin:jar:1.3.0.M5 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.springframework.boot:spring-boot-maven-plugin:1.3.0.M5: Plugin org.springframework.boot:spring-boot-maven-plugin:1.3.0.M5 or one of its dependencies could not be resolved: Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:1.3.0.M5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml

**Comment by rushan09** [comment]
Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:1.3.0.M5 in https://repo.maven.apache.org/maven2 was cached in the local 
 repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

still I am getting the same issue...

**Comment by luanne** [comment]
Please try forcing an update with mvn -U ...
